name: output

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go
    - name: Output
      run: |
        cat 08\ spellcasting.json |jq '.Spellcasting."Spell Lists"' > output/spell-list.json
        go run . monster >output/new-monster-list.json
        go run . spell >output/new-spell-description-list.json
        go run . magicitem >output/new-magic-itens-list.json
        go run . armor >output/new-armor-list.json
        go run . weapon >output/new-weapon-list.json
        go run . gear >output/new-gear-list.json
        go run . packs >output/new-packs-list.json
        go run . tools >output/new-tools-list.json
        go run . mounts >output/new-mounts-list.json
        go run . hoard >output/new-treasure-hoard-list.json
        go run . services >output/new-services-list.json
        ls output/